### ISSUE TITLE
Bahsetmenizi tavsiye ettiğim birkaç şey 

### ISSUE THREAD

**Issue by kaansenol5** [oldventura/digital_security_checklist#1]
# PiHole

PiHole, ağınızda DNS olarak kullanabileceğiniz, reklamları ve tracker'ları otomatik olarak engelleyen, ve hangi cihazın hangi siteye bağlandığını gösteren bir yazılım. Kullanmak için ihtiyacınız olan şey herhangi bir linux bilgisayar, ufak bir raspberry pi kullanabilirsiniz.

# Firefox

Firefox eklentisi olarak CookieAutoDelete ve ClearURLs i de öneririm, CookieAutoDelete whitelistlenmemiş cookie'leri otomatik olarak siler, ilk kurduğumda 1800 cookies deleted demişti baya şaşırmıştım. ClearURLs ise URL lerdeki takipçileri temizler. Örneğin https://www.reddit.com/r/MilletTemsilHeyeti/comments/nyuto0/dijital_güvenlik_kılavuzu/?utm_source=share&utm_medium=web2x&context=3 linkinden "?utm_source=share&utm_medium=web2x&context=3" kısmını siler.

# Linux Distro

Distro olarak yeni başlamış insanlara Arch, Manjaro ve Debian gibi distroları bir öneri sırası olmadan önermeniz pek mantıklı değil. Ubuntu'yu fazla bloated olduğu için önermemişsin. Ben şahsen yeni başlamış birisine Fedora'yı ya da Ubuntu'yu öneririm.

# Disk Encryption

Linux'ta güvenli olmak için **MUTLAKA** kurulum sırasında Full disk encryption'u seçmeniz gerek. Full disk encryption olmayan bir cihaz çalınır ise hırsızın bütün verilerinize erişmesi yaklaşık 60 saniye sürer. Bu durum Windows ve macOS için de geçerli, Windows'da BitLocker (biraz dandik ama hiç yoktan iyi) , macOS da ise ayarlarda bulabileceğiniz encryption u kullanın.

Not: Windows da bitlocker kurulumdan sonra aktive edilir, Linux da kurulumdan önce aktive edilir, macOS da ikisi de yapılabilir ama önce yapmanız tavsiyem.

# Linux Güvenlik Ekstra

Zoom, Steam, Discord, Spotify, Minecraft gibi uygulamaların hepsi https://flathub.org/ da flatpak paketleri olarak mevcuttur. Flatpak uygulamaları sistemin geri kalanından izole eden bir linux sistemidir. Bu tarz uygulamaları kendi sitelerindeki .deb veya .rpm dosyaları yerine flatpak olarak kurun. 

Ayrıca https://redd.it/ns7r7o linkinde anlatılan şeyler de yapılabilir, biraz abartı, bana gereksiz geldi.

# Password Manager

KeePassXC güvenli ve açık kaynaklı bir sistem, evet. Ama kullanması zor olabilir bazı insanlar için. Bu nedenle BitWarden dan da bahsetmenizi öneririm.

# Linux Uygulama Kurulumu Hakkında Bilgi

Linux'ta uygulama kurmak, Windows'daki gibi internet sitelerinden .exe indirip kurarak yapılmaz. Her linux distro'sunun bir paket yöneticisi bulunur, burada aklınıza gelen her şeyin yarısı mevcuttur. Uygulama indirmek için paket yöneticilerini kullanın. Fedora veya Ubuntu gibi dağıtımlardaki "Software Center" uygulaması ile ya da komut satırı ile kurabilirsiniz. Paket yöneticisinden asla (%99 diyelim) virüs bulaşmaz. Paket yöneticisinde bulamadığınız yazılımları ya flatpak olarak flathub'da, ya da snap store'da bulursunuz, o da yoksa uygulamanın sitesinde .deb ve .rpm vardır, o da yoksa kendi repoları vardır onu eklersiniz paket yöneticinize, o da yoksa kurmayın amk

**Comment by oldventura** [comment]
👍
